[project]
name = "korean-orberg"
version = "0.1.0"
description = "Korean language learning materials using the natural method"
readme = "CLAUDE.md"
requires-python = ">=3.9"
dependencies = [
    "ebooklib>=0.18",
    "markdown>=3.4.0",
]

[dependency-groups]
dev = []
